/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./**/*.html",
    "./**/*.js",
    "./*.html",
    "./src/**/*.html",
    "./src/**/*.js"
  ],
  theme: {
    extend: {
      colors: {
        'yinmn-blue': '#4c6085',
        'celestial-blue': '#39a0ed',
        'aquamarine': '#36f1cd',
        'mint': '#13c4a3',
        'black-olive': '#32322c',
      }
    },
  },
  plugins: [],
  safelist: [
  "bg-gray-100",
  "text-black-olive",
  "dark:bg-black-olive",
  "dark:text-gray-100",
  "fixed",
  "top-0",
  "left-0",
  "w-full",
  "bg-yinmn-blue",
  "text-white",
  "flex",
  "items-center",
  "p-4",
  "shadow-md",
  "z-20",
  "flex-col",
  "gap-1",
  "cursor-pointer",
  "w-6",
  "h-1",
  "bg-white",
  "rounded",
  "ml-4",
  "text-xl",
  "font-bold",
  "ml-auto",
  "h-6",
  "h-full",
  "w-64",
  "bg-black-olive",
  "transform",
  "-translate-x-full",
  "transition-transform",
  "duration-300",
  "z-10",
  "mt-20",
  "gap-4",
  "p-6",
  "text-lg",
  "font-semibold",
  "hover:text-mint",
  "inset-0",
  "bg-black",
  "bg-opacity-50",
  "hidden",
  "z-5",
  "pt-20",
  "px-6",
  "max-w-4xl",
  "mx-auto",
  "text-center",
  "py-12",
  "text-3xl",
  "text-yinmn-blue",
  "mt-4",
  "mt-8",
  "rounded-lg",
  "dark:bg-neutral-800",
  "grid",
  "grid-cols-5",
  "w-16",
  "h-16",
  "border",
  "border-gray-200",
  "mt-2",
  "text-sm",
  "text-gray-700",
  "bg-celestial-blue",
  "bg-aquamarine",
  "bg-mint",
  "min-h-[calc(100svh-5rem)]",
  "place-items-center",
  "text-left",
  "max-w-2xl",
  "leading-relaxed",
  "block",
  "text-justify",
  "text-blue-900",
  "hover:underline",
  "relative",
  "group",
  "z-30",
  "absolute",
  "-left-36",
  "top-1/2",
  "-translate-y-1/2",
  "whitespace-nowrap",
  "bg-black/80",
  "px-3",
  "py-1",
  "opacity-0",
  "scale-95",
  "group-hover:opacity-100",
  "group-hover:scale-100",
  "transition-all",
  "duration-150"
],
}
